/*
View: Test-Group-View-Master
*/
USE LIMSDB;
CREATE VIEW TEST_GROUP_VIEW AS
    SELECT 
    TGPM.GPIX as GroupId,TGPM.TPARAM as ParamId,TGPM.TMETH as MethodId,TG01.NAME as GroupValue,TG01.DESC as GroupDesc,
    TM01.NAME as ParamValue,TM01.DESC as ParamDesc,
    TM02.NAME as MethodValue,TM02.DESC as MethodDesc,TM02.XUNIT as UoM,TM02.XFLAG as XFLAG
    FROM TGPM
    LEFT OUTER JOIN TG01 ON (TGPM.GPIX=TG01.GPIX)
    LEFT OUTER JOIN TM01 ON (TGPM.TPARAM=TM01.TPARAM)
    LEFT OUTER JOIN TM02 ON (TGPM.TPARAM=TM02.TPARAM) AND (TGPM.TMETH=TM02.TMETH);

